---

stages:
  - lint
  - test


pylint:
  stage: lint
  image: snakepacker/python:all
  before_script:
    - python3.10 -m pip install poetry
    - poetry install
  script:
    - poetry run pylint app tests

pytest:
  stage: test
  image: snakepacker/python:all
  services:
    - name: postgres:14
  variables:
    POSTGRES_DB: app_db
    POSTGRES_USER: user
    POSTGRES_PASSWORD: hackme
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
  before_script:
    - python3.10 -m pip install poetry
    - poetry install
    - wait-for-port postgres:5432
  script:
    - poetry run pytest --verbosity=2 --showlocals --log-level=DEBUG --cov=app --cov-report html
