"""empty message

Revision ID: d273d522fdd2
Revises: 6e672dcd46a5
Create Date: 2023-03-30 14:56:59.793531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd273d522fdd2'
down_revision = '6e672dcd46a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('recipient_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk__participant__recipient_id__participant'), 'participant', 'participant', ['recipient_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__participant__recipient_id__participant'), 'participant', type_='foreignkey')
    op.drop_column('participant', 'recipient_id')
    # ### end Alembic commands ###
