"""empty message

Revision ID: 516e5890765a
Revises: 2f9e33a37a52
Create Date: 2023-03-30 15:34:58.252878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516e5890765a'
down_revision = '2f9e33a37a52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
