"""empty message

Revision ID: 5fec43c16e17
Revises: c790650ee84d
Create Date: 2023-03-30 15:07:49.930220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fec43c16e17'
down_revision = 'c790650ee84d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
