"""empty message

Revision ID: df653f494acf
Revises: 4a21476c1381
Create Date: 2023-03-30 15:03:57.899261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df653f494acf'
down_revision = '4a21476c1381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
