"""empty message

Revision ID: 74a808eaff59
Revises: b4f2c5803bc9
Create Date: 2023-03-30 14:40:10.593231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a808eaff59'
down_revision = 'b4f2c5803bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq__group__id'), 'group', ['id'])
    op.add_column('participant', sa.Column('recipient_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f('uq__participant__id'), 'participant', ['id'])
    op.create_foreign_key(op.f('fk__participant__recipient_id__participant'), 'participant', 'participant', ['recipient_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__participant__recipient_id__participant'), 'participant', type_='foreignkey')
    op.drop_constraint(op.f('uq__participant__id'), 'participant', type_='unique')
    op.drop_column('participant', 'recipient_id')
    op.drop_constraint(op.f('uq__group__id'), 'group', type_='unique')
    # ### end Alembic commands ###
