"""empty message

Revision ID: b4f2c5803bc9
Revises: 
Create Date: 2023-03-30 14:13:00.093376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f2c5803bc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__group')),
    sa.UniqueConstraint('id', name=op.f('uq__group__id'))
    )
    op.create_table('participant',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('wish', sa.TEXT(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('fk__participant__group_id__group'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__participant')),
    sa.UniqueConstraint('id', name=op.f('uq__participant__id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant')
    op.drop_table('group')
    # ### end Alembic commands ###
