"""empty message

Revision ID: ca5cb86bae18
Revises: df653f494acf
Create Date: 2023-03-30 15:05:26.678931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca5cb86bae18'
down_revision = 'df653f494acf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
