"""empty message

Revision ID: 77e460a4560c
Revises: 5fec43c16e17
Create Date: 2023-03-30 15:09:43.273045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e460a4560c'
down_revision = '5fec43c16e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
