"""empty message

Revision ID: 6c526fc92351
Revises: 77e460a4560c
Create Date: 2023-03-30 15:15:41.776050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c526fc92351'
down_revision = '77e460a4560c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
