"""empty message

Revision ID: edc68cb15b6f
Revises: 6c526fc92351
Create Date: 2023-03-30 15:18:09.439291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edc68cb15b6f'
down_revision = '6c526fc92351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
