"""empty message

Revision ID: a1e8ad938340
Revises: 74a808eaff59
Create Date: 2023-03-30 14:44:34.928135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e8ad938340'
down_revision = '74a808eaff59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
