"""empty message

Revision ID: 2f9e33a37a52
Revises: 4b79523d549d
Create Date: 2023-03-30 15:31:32.017835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f9e33a37a52'
down_revision = '4b79523d549d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
