"""empty message

Revision ID: 4a21476c1381
Revises: d273d522fdd2
Create Date: 2023-03-30 15:00:38.810651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a21476c1381'
down_revision = 'd273d522fdd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
